spring:
  application:
    name: blackjack-api

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false

  datasource:
    url: jdbc:mysql://mysql:3306/blackjack_games
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: TU_USUARIO_MYSQL
    password: TU_CONTRASENA_MYSQL

  data:
    mongodb:
      uri: mongodb://admin:admin@mongodb:27017/blackjack_games?authSource=admin

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
  api-docs:
    path: /v3/api-docs
    enabled: true

server:
  port: 8080

logging:
  level:
    root: INFO
    com.blackjack: DEBUG